apiVersion: v1
kind: Service
metadata:
  name: dvwa-mysql-service
  labels:
    app: dvwa-mysql
spec:
  selector:
    app: dvwa-mysql
    tier: backend
  type: ClusterIP  # Internal service for MySQL
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
